server:
  port: 8088


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/lottery?useUnicode=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    root: debug #基础日志级别
#    com.baidu.pk1: info     #pk1包下的类使用info级别
#    com.baidu.pk2: debug    #pk2包下的类使用debug级别

#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml #不能和configuration同时配置

#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
#      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 多数据源路由配置
mini-db-router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 4
      default: db00
      routerKey: uId
      list: db01,db02
      db00:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lottery?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
        username: root
        password: 123456
      db01:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lottery_01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
        username: root
        password: 123456
      db02:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lottery_02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
        username: root
        password: 123456

# Dubbo 广播方式配置
dubbo:
  application:
    name: Lottery
    version: 1.0.0
#    parameters:
#      unicast: false
  registry:
    address: N/A #multicast://10.157.101.166:1234
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: org.example.rpc
  provider:
    timeout: 1000000
